name: telegram-desktop
adopt-info: telegram
icon: Telegram/Resources/art/icon512@2x.png

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  telegram-desktop:
    command: usr/bin/telegram-desktop
    command-chain:
      - bin/desktop-launch
    common-id: org.telegram.desktop
    desktop: usr/share/applications/org.telegram.desktop.desktop
    autostart: telegram-desktop_telegram-desktop.desktop
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - hardware-observe
      - home
      - network
      - network-bind
      - network-status
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11
    slots:
      - mpris

hooks:
  configure:
    command-chain:
      - bin/hooks-configure-desktop
    plugs:
      - desktop

plugs:
  desktop:
    mount-host-font-cache: false
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/pipewire:
    bind: $SNAP/usr/share/pipewire
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$CRAFT_ARCH_TRIPLET/gtk-3.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gtk-3.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3
  /usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1

package-repositories:
  - type: apt
    ppa: kisak/kisak-mesa

parts:
  telegram:
    plugin: nil
    source: .
    source-type: git
    parse-info: [lib/xdg/org.telegram.desktop.metainfo.xml]
    build-packages:
      - curl
      - tar
    stage-packages:
      - libasound2
      - libdbus-1-3
      - libdrm2
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libgbm1
      - libgl1
      - libglib2.0-0
      - libgtk-3-0
      - libpulse0
      - libva2
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebkit2gtk-4.1-0
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - glib-networking
      - pipewire
      - va-driver-all
      - vdpau-driver-all
    override-pull: |
      craftctl default

      version_file=Telegram/build/version
      version=$(sed -n "s/AppVersionStr[ ]\+\(.*\)\+/\1/p" $version_file)
      beta=$(sed -n "s/BetaChannel[ ]\+\(.*\)\+/\1/p" $version_file)

      curl -sSL https://github.com/telegramdesktop/tdesktop/releases/download/v$version/tsetup.$version.tar.xz | tar -xJ --one-top-level=out

      if [ "$beta" != "0" ]; then
        version="$version-beta"
      fi

      version="${version}$(git describe --tags | sed 's,^v[^-]\+,,')"

      craftctl set version="$version"

      sed -i 's|^Icon=telegram$|Icon=${SNAP}/meta/gui/icon.png|g' lib/xdg/org.telegram.desktop.desktop
    override-build: |
      mkdir -p "$CRAFT_PART_INSTALL/usr/bin" "$CRAFT_PART_INSTALL/usr/share/applications" "$CRAFT_PART_INSTALL/usr/share/TelegramDesktop/externalupdater.d"
      mv out/Telegram/Telegram "$CRAFT_PART_INSTALL/usr/bin/telegram-desktop"
      mv lib/xdg/org.telegram.desktop.desktop "$CRAFT_PART_INSTALL/usr/share/applications"
      echo "$CRAFT_PART_INSTALL/bin/telegram-desktop" > "$CRAFT_PART_INSTALL/usr/share/TelegramDesktop/externalupdater.d/00-main"

  desktop-qt:
    source: https://github.com/desktop-app/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
      - gtk-update-icon-cache
      - libglib2.0-bin
      - libgtk-3-0
    stage-packages:
      - libc-bin
      - libgdk-pixbuf-2.0-0
      - libxkbcommon0
      - locales-all
      - shared-mime-info
      - xdg-user-dirs
    override-prime: |
      craftctl default
      update-mime-database usr/share/mime
      glib-compile-schemas usr/share/glib-2.0/schemas
      for theme in usr/share/icons/*; do
        if [ -f "$theme/index.theme" ] && [ ! -f "$theme/icon-theme.cache" ]; then
          update-icon-caches "$theme"
        fi
      done
      GTK_PATH=$PWD/usr/lib/$CRAFT_ARCH_TRIPLET/gtk-3.0 /usr/lib/$CRAFT_ARCH_TRIPLET/libgtk-3-0/gtk-query-immodules-3.0 > usr/lib/$CRAFT_ARCH_TRIPLET/gtk-3.0/3.0.0/immodules/immodules.cache
    after:
      - telegram

  systemd:
    plugin: nil
    stage-packages:
      - systemd
    stage:
      - ./usr/bin/systemd-detect-virt
