name: telegram-desktop
adopt-info: telegram

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  telegram-desktop:
    command: usr/bin/telegram-desktop
    common-id: org.telegram.desktop
    desktop: usr/share/applications/org.telegram.desktop.desktop
    autostart: telegram-desktop_telegram-desktop.desktop
    extensions: [gnome]
    plugs:
      - audio-playback
      - audio-record
      - camera
      - hardware-observe
      - home
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
    slots:
      - mpris

parts:
  telegram:
    plugin: nil
    source: .
    source-type: git
    parse-info: [lib/xdg/org.telegram.desktop.metainfo.xml]
    build-packages:
      - curl
      - tar
    override-pull: |
      craftctl default

      version_file=Telegram/build/version
      version=$(sed -n "s/AppVersionStr[ ]\+\(.*\)\+/\1/p" $version_file)
      beta=$(sed -n "s/BetaChannel[ ]\+\(.*\)\+/\1/p" $version_file)

      curl -sSL https://github.com/telegramdesktop/tdesktop/releases/download/v$version/tsetup.$version.tar.xz | tar -xJ --one-top-level=out

      if [ "$beta" != "0" ]; then
        version="$version-beta"
      fi

      version="${version}$(git describe --tags | sed 's,^v[^-]\+,,')"

      craftctl set version="$version"
    override-build: |
      mkdir -p "$CRAFT_PART_INSTALL/usr/bin" "$CRAFT_PART_INSTALL/usr/share/applications" "$CRAFT_PART_INSTALL/usr/share/TelegramDesktop/externalupdater.d"
      mv out/Telegram/Telegram "$CRAFT_PART_INSTALL/usr/bin/telegram-desktop"
      mv lib/xdg/org.telegram.desktop.desktop "$CRAFT_PART_INSTALL/usr/share/applications"
      echo "$CRAFT_PART_INSTALL/bin/telegram-desktop" > "$CRAFT_PART_INSTALL/usr/share/TelegramDesktop/externalupdater.d/00-main"

  geoclue:
    plugin: nil
    stage-packages:
      - libgeoclue-2-0
    stage:
      - ./usr/lib/x86_64-linux-gnu/libgeoclue-2.so*

  systemd:
    plugin: nil
    stage-packages:
      - systemd
    stage:
      - ./usr/bin/systemd-detect-virt
