name: Linux.

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'
      - 'snap/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'
      - 'snap/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'

jobs:

  linux:
    name: Rocky Linux 8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defines:
          - ""
          - "DESKTOP_APP_DISABLE_X11_INTEGRATION"

    env:
      IMAGE_TAG: tdesktop:centos_env

    steps:
      - name: Clone.
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: First set up.
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -

          echo "${{ hashFiles('Telegram/build/docker/centos_env/**') }}" >> CACHE_KEY.txt
          echo "${{ hashFiles('Telegram/ThirdParty/vcpkg/scripts/vcpkg-tool-metadata.txt') }}" >> CACHE_KEY.txt
          echo "${{ hashFiles('vcpkg.json') }}" >> CACHE_KEY.txt
          echo "${{ hashFiles('vcpkg-configuration.json') }}" >> CACHE_KEY.txt
          echo "${{ hashFiles('Telegram/build/patches/vcpkg/**') }}" >> CACHE_KEY.txt
          echo "${{ hashFiles('conanfile.py') }}" >> CACHE_KEY.txt

          cd Telegram/build/docker/centos_env
          poetry install
          DOCKERFILE=$(DEBUG= LTO= poetry run gen_dockerfile)
          echo "$DOCKERFILE" > Dockerfile
          rm -rf __pycache__

      - name: Free up some disk space.
        uses: endersonmenezes/free-disk-space@6c4664f43348c8c7011b53488d5ca65e9fc5cd1a
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle"
          rm_cmd: "rmz"
          rmz_version: "3.1.1"

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Libraries cache.
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.temp }}/.buildx-cache
            .cache/vcpkg/archives
            .cache/conan/p
          key: ${{ runner.OS }}-libs-${{ hashFiles('CACHE_KEY.txt') }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Libraries.
        uses: docker/build-push-action@v6
        with:
          context: Telegram/build/docker/centos_env
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Move cache.
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache{-new,}

      - name: Telegram Desktop build.
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=Telegram_${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram" >> $GITHUB_ENV
          fi

          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          -e CONFIG=Release \
          -e GITHUB_ACTIONS \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D CMAKE_C_FLAGS_RELEASE="-O0" \
          -D CMAKE_CXX_FLAGS_RELEASE="-O0" \
          -D CMAKE_EXE_LINKER_FLAGS_RELEASE="-fuse-ld=lld" \
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON \
          -D TDESKTOP_API_TEST=ON \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
          $DEFINE

      - uses: actions/upload-artifact@v5
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/Release
