name: MacOS.

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/mac.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/configure.bat'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/mac.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/configure.bat'

jobs:

  macos:
    name: MacOS
    runs-on: macos-latest

    strategy:
      matrix:
        defines:
          - ""

    steps:
      - name: Get repository name.
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v6
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        run: |
          brew update
          brew upgrade || true
          brew install autoconf autoconf-archive automake libtool nasm
          mkdir Libraries
          ln -s $VCPKG_INSTALLATION_ROOT Libraries/vcpkg
          echo "$(Libraries/vcpkg/vcpkg --version | head -n1 | cut -d' ' -f6)" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/vcpkg.json', env.REPO_NAME)) }}" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/vcpkg-configuration.json', env.REPO_NAME)) }}" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/Telegram/build/patches/vcpkg/**', env.REPO_NAME)) }}" >> CACHE_KEY.txt

      - name: Free up some disk space.
        uses: hugoalh/disk-space-optimizer-ghaction@271735125a1b35180620eae7e45c2e9d470c31b0
        with:
          general_include: ".+"
          general_exclude: "VCPkg"
          homebrew_prune: "True"
          homebrew_clean: "True"
          npm_prune: "True"
          npm_clean: "True"

      - name: Libraries cache.
        uses: actions/cache@v4
        with:
          path: Libraries/.cache/vcpkg/archives
          key: ${{ runner.OS }}-libs-${{ hashFiles('CACHE_KEY.txt') }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Telegram Desktop build.
        run: |
          cd $REPO_NAME
          ARTIFACT_NAME="Telegram"

          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=${ARTIFACT_NAME}_${{ matrix.defines }}"
          fi

          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

          cmake \
          --preset Release \
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON \
          -D VCPKG_HOST_TRIPLET=arm64-osx-release \
          -D VCPKG_TARGET_TRIPLET=arm64-osx-release \
          -D TDESKTOP_API_TEST=ON \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
          $DEFINE

          cmake --build out/Release --parallel

      - uses: actions/upload-artifact@v5
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.REPO_NAME }}/out/Release
