name: Windows.

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-win*.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-win*.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'

jobs:

  windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [Win32, x64]
        generator: ["", "Ninja Multi-Config"]

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\Libraries

    defaults:
      run:
        shell: cmd

    steps:
      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v6
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        shell: bash
        run: |
          mkdir Libraries
          DOCPATH=$REPO_NAME/docs/building-win.md
          [ "${{ matrix.arch }}" != Win32 ] && DOCPATH=$REPO_NAME/docs/building-win-${{ matrix.arch }}.md
          SDK="$(grep "SDK version" $DOCPATH | sed -r 's/.*\*\*(.*)\*\* SDK version.*/\1/')"
          echo "SDK=$SDK" >> $GITHUB_ENV
          echo "$SDK" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/vcpkg.json', env.REPO_NAME)) }}" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/vcpkg-configuration.json', env.REPO_NAME)) }}" >> CACHE_KEY.txt
          echo "${{ hashFiles(format('{0}/Telegram/build/patches/vcpkg/**', env.REPO_NAME)) }}" >> CACHE_KEY.txt

      - uses: ilammy/msvc-dev-cmd@v1.13.0
        name: Native Tools Command Prompt.
        with:
          arch: ${{ matrix.arch }}
          sdk: ${{ env.SDK }}

      - name: vcpkg set up.
        shell: bash
        run: |
          sed -i 's@/Z7 @@g; s@/DEBUG @@g' "$VCPKG_ROOT"/scripts/toolchains/windows.cmake
          echo "$("$VCPKG_ROOT"/vcpkg --version | head -n1 | cut -d' ' -f6)" >> CACHE_KEY.txt

      - name: Setup Conan Client.
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Libraries cache.
        uses: actions/cache@v4
        with:
          path: Libraries
          key: ${{ runner.OS }}-${{ matrix.arch }}-libs-${{ hashFiles('CACHE_KEY.txt') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.arch }}-libs-

      - name: Read configuration matrix.
        shell: bash
        run: |
          ARTIFACT_NAME="Telegram"

          ARCH=""
          if [ -n "${{ matrix.arch }}" ]; then
            case "${{ matrix.arch }}" in
              Win32) ARCH="x86";;
              *) ARCH="${{ matrix.arch }}";;
            esac
            echo "Architecture from matrix: $ARCH"
            ARTIFACT_NAME="${ARTIFACT_NAME}_${{ matrix.arch }}"
          fi

          GENERATOR=""
          if [ -n "${{ matrix.generator }}" ]; then
            GENERATOR="-G \"${{ matrix.generator }}\""
            echo "Generator from matrix: $GENERATOR"
            ARTIFACT_NAME="${ARTIFACT_NAME}_${{ matrix.generator }}"
          fi
          echo "TDESKTOP_BUILD_GENERATOR=$GENERATOR" >> $GITHUB_ENV

          [ -n "$GENERATOR" ] && ARCH=""
          echo "TDESKTOP_BUILD_ARCH=$ARCH" >> $GITHUB_ENV

          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo "Define from matrix: $DEFINE"
            ARTIFACT_NAME="${ARTIFACT_NAME}_${{ matrix.defines }}"
          fi
          echo "TDESKTOP_BUILD_DEFINE=$DEFINE" >> $GITHUB_ENV

          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

          API="-D TDESKTOP_API_TEST=ON"
          if [ $GITHUB_REF == 'refs/heads/nightly' ]; then
            echo "Use the open credentials."
            API="-D TDESKTOP_API_ID=611335 -D TDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c"
          fi
          echo "TDESKTOP_BUILD_API=$API" >> $GITHUB_ENV

      - name: Telegram Desktop build.
        run: |
          cd %REPO_NAME%\Telegram

          call configure.bat ^
          %TDESKTOP_BUILD_GENERATOR% ^
          %TDESKTOP_BUILD_ARCH% ^
          %TDESKTOP_BUILD_API% ^
          -D CMAKE_CONFIGURATION_TYPES=Release ^
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON ^
          -D CMAKE_MSVC_DEBUG_INFORMATION_FORMAT= ^
          -D VCPKG_OVERLAY_TRIPLETS=%GITHUB_WORKSPACE%\%REPO_NAME%\Telegram\build\patches\vcpkg\ci-triplets ^
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF ^
          %TDESKTOP_BUILD_DEFINE%

          cmake --build ..\out --config Release --parallel

      - uses: actions/upload-artifact@v5
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.REPO_NAME }}\out\Release
